### ISSUE TITLE
Status: ERROR 5: Connection Was Terminated.

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/ussd-gui#1] opened 2016-04-20 13:48 UTC
I'm just testing ussd-gui on debian SID, and it works as expected. But there's one thing I can't figure out. Some of the USSD codes have to be answered. In that case, you have to send 0, 1, etc. When I do it via the following AT command:

```
$ echo -e "AT+CUSD=1,\"*111#\",15\r" >/dev/huawei-E3372-0
```

I'm able to receive the proper answer and respond to it by sending, for instance `1`:

```
$ echo -e "AT+CUSD=1,\"1\",15\r" >/dev/huawei-E3372-0
```

After this I get another answer, and so on. Of course, I have to `cat` the device while sending the AT commands in order to see the results, but generally this works well.

When I want to do the same with ussd-gui, I get an error: `Status: ERROR 5: Connection Was Terminated`. I wasn't able to respond to any USSD codes. Is this app able to do it?

**Comment by mhogomchungu** [comment] 2016-04-20 14:16
What is the output of the following command

```
gammu --version

```

That command will give us the version of libgammu you are using.

Yes,the app can do it and it can also auto send those responses by separating them with a space character,for example,a command of: `*149*01# 5 1 2` will send the `*149*01#` command and then responds with a "5",then responds again with a "1" and finally responds with a "2". Not sure if the released version has this feature but the git version does.

The problem you are having is most likely on the libgammu's end. Do you get a short hang after you send your request? I think there is a very short response window and the connection gets terminated when you do not respond soon enough.

**Comment by morfikov** [comment] 2016-04-20 14:28
This is the version:

```
$ gammu --version
[Gammu version 1.37.2]
```

I'm using the git version of ussd-gui because of the info in the commits.

So I have to send the answers along with the USSD code? I mean, for instance, `*149*01# 5 1 2` and not `*149*01#` and then `5` , `1` and `2` ? Anyways, I tested the full code and there's the same situation. 

After sending the code, I get `Status: Waiting For A Reply .... .... ....` and the three dots appear in 1s till the `timeout` is reached. After that, there's some delay/hang and nothing happens for some seconds, and after that I get the `Status: ERROR 5: Connection Was Terminated.` message.

**Comment by mhogomchungu** [comment] 2016-04-20 15:21
No,you do not have to send the responses along with the USSD code.

You can send only the USSD code and then each answer or you can send the USSD code along with the answers,which one you prefer is up to you. I just though of mentioning the alternative in case you will find it useful.

Can you send your command using gammu CLI utility? The problem is most likely on gammu and i am not sure how i can solve it on my end.

**Comment by morfikov** [comment] 2016-04-20 15:23
What command should I send?

**Comment by mhogomchungu** [comment] 2016-04-20 15:32
The command should be:

```
gammu getussd USSD
```

Last time i checked,it was not possible to send responses,maybe newer versions have added support for it.

with ussd-gui,you can see generated log output by starting it from the terminal with "-d" option. Maybe the generated log output will shed some light on the problem.

**Comment by morfikov** [comment] 2016-04-20 15:51
Should the `gammu getussd` command be delayed for about 1-2 minutes? When I use the following command:

```
gammu getussd "*111#"
```

I have to wait for about 1-2min till I get an answer which is the following:

```
$ gammu getussd "*111#"
Press Ctrl+C to break...
USSD received
Status               : Action needed
Service reply        : "Fakt Mobile Menu
1 Konto
2 Uslugi / Promocje
0 Wyjscie
Wiecej opcji znajdziesz na http://faktmobile.pl i http://24.play.pl"
```

 I don't know why gammu is so slow, but I can't respond to this answer.

The following is the log from ussd-gui after replying to the answer:

```
Entering GSM_SetIncomingUSSD
Enabling incoming USSD
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D                          AT+CUSD=1.
1 "AT+CUSD=1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=1...OK..
Leaving GSM_SetIncomingUSSD
Entering GSM_DialService
SENDING frame type 0x00/length 0x12/18
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|333|311|22"|2C,|311 AT+CUSD=1,"31",1
355|0D                                                          5.
1 "AT+CUSD=1,"31",15"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x18/24
41A|54T|2B+|43C|55U|53S|44D|3D=|311|2C,|22"|333|311|22"|2C,|311 AT+CUSD=1,"31",1
355|0D |0D |0A |4FO|4BK|0D |0A                                  5...OK..
Incoming USSD received
Leaving GSM_DialService
Entering GSM_SetIncomingUSSD
Terminating possible incoming USSD
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|322|0D                          AT+CUSD=2.
1 "+CUSD: 2"
2 "AT+CUSD=2"
3 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x1A/26
2B+|43C|55U|53S|44D|3A:|20 |322|0D |0A |41A|54T|2B+|43C|55U|53S +CUSD: 2..AT+CUS
44D|3D=|322|0D |0D |0A |4FO|4BK|0D |0A                          D=2...OK..
Incoming USSD received
Parsing +CUSD: 2
AT+CUSD=2
OK
 with +CUSD: @i @0
Parsed int 2
Status: 2
Parsing +CUSD: 2
AT+CUSD=2
OK
 with +CUSD: @i, @r, @i @0
Parsed int 2
Parsing +CUSD: 2
AT+CUSD=2
OK
 with +CUSD: @i, @r @0
Parsed int 2
coding 0 -> 3
Performing device reset after timeout!
Entering GSM_Reset
Resetting device
SENDING frame type 0x00/length 0x0C/12
41A|54T|2B+|43C|46F|55U|4EN|3D=|311|2C,|311|0D                  AT+CFUN=1,1.
1 "AT+CFUN=1,1"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x12/18
41A|54T|2B+|43C|46F|55U|4EN|3D=|311|2C,|311|0D |0D |0A |4FO|4BK AT+CFUN=1,1...OK
0D |0A                                                          ..
Reset done
Leaving GSM_Reset
Disabling incoming USSD
SENDING frame type 0x00/length 0x0A/10
41A|54T|2B+|43C|55U|53S|44D|3D=|300|0D                          AT+CUSD=0.
1 "AT+CUSD=0"
2 "OK"
Checking line: OK
AT reply state: 1
RECEIVED frame type 0x00/length 0x10/16
41A|54T|2B+|43C|55U|53S|44D|3D=|300|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=0...OK..
Leaving GSM_SetIncomingUSSD
```

I have no idea how to read it.

**Comment by mhogomchungu** [comment] 2016-04-20 21:31
you can increase the timeout period by changing the "timeout" field in ussd-gui config file located at "~/.config/ussd-gui/ussd-gui.config"

the timeout is in seconds.

i think the delay of one or two minutes is too long. Perhaps gammu project does not work very well with your hardware,as a front end to libgammu,there is very little i can with hardware that is not very well supported in libgammu.

**Comment by mhogomchungu** [comment] 2016-04-21 17:02
Did changing the "timeout" option in ussd-gui make a difference?

From where can i know more about the commands you were manually sending?

I have always wanted to have an internal backend that send and receive ussd codes but have no idea where to start looking for the info.

**Comment by morfikov** [comment] 2016-04-21 17:16
I've set `timeout=120` in the `~/.config/ussd-gui/ussd-gui.conf`file, but there's no difference, except waiting. 

As for the AT commands I've echoed to the file in /dev/ , I haven't find any good source of information. I just found some commands that proved to be useful. Sometimes I'm using `wvdial`. You can check my config for `wvdial` [1]. I've collected some info there, but it's all I've got by searching the internet. Unfortunately, you can't send SMS and USSD via `wvdial`.

[1] https://github.com/morfikov/files/blob/master/configs/etc/wvdial.conf

**Comment by mhogomchungu** [comment] 2016-04-25 10:42
I am closing this one as "cant fix" since the problem you are experiencing is due to libgammu not supporting your hardware very well.

I just made a commit[1] that made it possible to have additional backends that can be changed at runtime. I will look into adding an internal backed[2] that will do what you did above,writing to device straight and reading from it straight.It seems simple enough from the little test i have done.

One question,how i do disconnect using wvdial? It seems all i have to do to connect is to run it but i can not see a way to disconnect using wvdial.

[1] https://github.com/mhogomchungu/ussd-gui/commit/930c8b41016e3ef74f0e66efbe5c284f4614fbba

[2] https://github.com/mhogomchungu/ussd-gui/blob/930c8b41016e3ef74f0e66efbe5c284f4614fbba/src/internal.cpp

**Closed as completed by mhogomchungu** 2016-04-25 10:42 UTC

**Comment by morfikov** [comment] 2016-04-25 11:02
`wvdial` most of the time is used to connect via USB LTE modem in RAS mode (PPP daemon). But in this case, i.e. when you want send SMS/USSD you don't have to connect to anything. You just set an appropriate modes via:

Prefer LTE mode, but also enable UMTS/GSM needed for SMS/USSD:

```
AT^SYSCFGEX="030201",3FFFFFFF,1,2,800C5,,
AT+CMGF=1;^CURC=0;^USSDMODE=0 
```

I don't know whether the second command has to be specified. I've seen people using this command when they wanted to send SMS/USSD.

And you can send codes (*107#):

```
AT+CUSD=1,"*107#",15
```

and reply to the answers (2):

```
AT+CUSD=1,"2",15
```

You don't have to disconnect because you aren't connected to anything because you don't have to in order to send SMS/USSD .

I think, the hardest part is to target the appropriate device. Maybe that could be specified by the user in options?

**Comment by mhogomchungu** [comment] 2016-04-25 11:24
I think a user will have to specify the device when internal back end is in use.

**Comment by mhogomchungu** [comment] 2016-04-25 13:50
Internal backend now "works for me" and it currently looks like this[1]

Will appreciate if you could confirm that it works. 

After you have successfully build ussd-gui,add the following two lines to your "ussd.config" file and start it and test it.

```
source=internal
device=/dev/huawei-E3372-0
```

Make sure you can interact with your device with "echo" and "cat" first before testing.

[1] https://github.com/mhogomchungu/ussd-gui/blob/master/src/internal.cpp

**Comment by morfikov** [comment] 2016-04-25 15:23
I've just tested, and it doesn't work. I'm able to send AT commands via `echo` and `cat` the appropriate device, but in `source=internal` I was unable to receive any answer. I just get the following message:

```
Status: ERROR 3: No Response Within 30 Seconds.
```

I tried to set 10,30,60 seconds,  but it didn't help. The old method works fine.

It looks like the problem is inside `ussd-gui` because when I send the code `*121#` using this program, I got the answer to the terminal (while cat'ing the device). So the answer comes, but `ussd-gui` is unable to display it and instead it gives the message above.

**Comment by mhogomchungu** [comment] 2016-04-25 15:39
start the program from the terminal with "-d" option and post its output

**Comment by mhogomchungu** [comment] 2016-04-25 15:41
run ussd-gui without having terminal running and hanged on the "cat" command,this command seems to read all data from the device leaving ussd-gui with nothing to read.

**Comment by morfikov** [comment] 2016-04-25 15:47
Yes, but I tested it without cat'ing, I just wanted to check whether the code was sent.

There's no output when I start `ussd-gui -d` from terminal. When I use `source=libgammu` then I get debug info on the terminal.

**Comment by mhogomchungu** [comment] 2016-04-25 15:57
Do you run the application from your user account or from root's account?

If from your user account,do you have write and read access to the device?

Can you update to the latest git and try again and see if the GUI application will report any errors when it failed to send the code.

**Comment by morfikov** [comment] 2016-04-25 16:02
From the user account. And yes I have the rights: 

```
$ ls -al /dev/huawei-E3372-* /dev/ttyUSB*
lrwxrwxrwx 1 root root         7 2016-04-25 16:45:49 /dev/huawei-E3372-0 -> ttyUSB0
lrwxrwxrwx 1 root root         7 2016-04-25 16:45:49 /dev/huawei-E3372-1 -> ttyUSB1
crw-rw---- 1 root dialout 188, 0 2016-04-25 17:46:59 /dev/ttyUSB0
crw-rw---- 1 root dialout 188, 1 2016-04-25 17:46:34 /dev/ttyUSB1

 $ id
uid=1000(morfik) gid=1000(morfik) groups=1000(morfik),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),30(dip),44(video),46(plugdev),100(users),101(systemd-journal),116(scanner),122(vboxusers),123(wireshark),127(debian-tor),5001(dane),5004(p2p),5005(cgroups),5010(hugepages)
```

I will update in a minute and see if that helps.

**Comment by morfikov** [comment] 2016-04-25 16:16
```
$ ussd-gui -d
"AT+CUSD=1,\"*121#\",15"
```

I think there's missing `\r` at the end, before the last `"`

**Comment by mhogomchungu** [comment] 2016-04-25 16:24
I coded the application's behavior based on what my modem was responding and the reason why its not working for you maybe because your modem responds differently.

Can you post the cat output when you send your commands?

**Comment by mhogomchungu** [comment] 2016-04-25 16:32
here is an example output here where things work:

The first response seems to be an echo of the command that is sent and then second response seems to be the response from the server and i dont see why you are not getting the second response.

Posting the "cat" command ouput when you send requests may shed some light with what is going on.

In case you are wondering the response language is "Swahili",the most widely used language in East Africa.I am in Tanzania.

```
[mtz@ink ~]$ ussd-gui -d
"AT+CUSD=1,"*149*01#",15" 
"
OK

+CUSD: 1,"Vodacom
1. Mpango Mzima(MPYA)
2. Vodacom RED
3. Ongea Deilee
4. Ofa kwa ajili Yako
5. Cheka
6. Intaneti
7. Nipige Tafu
8. Shangwe
9. Huduma Nyingine
10. Language ",15" 
"
AT+CUSD=1,"6",15" 
"
OK

+CUSD: 1,"1. Vifurushi vya Intaneti
2. Mpango Mzima(MPYA)
3. Salio la Intaneti
4. Blackberry
5. Ushauri wa Intaneti
6. Vodacom Live
7. Kudhibiti Data
8. Mnunulie Mwingine ",15" 
[mtz@ink ~]$ 
```

**Comment by morfikov** [comment] 2016-04-25 16:48
Should I use ussd-gui or just echo/cat ? In the second case:

![ussd](https://cloud.githubusercontent.com/assets/3797768/14791427/1473a70e-0b16-11e6-9e13-0086c3380117.png)

**Comment by mhogomchungu** [comment] 2016-04-25 17:03
The output above explains the problem.

The first response gets parsed correctly because its ends with `"\",15"`[1]

The second response does not get parsed correctly because the response is expected to end with `"\",15"`[2] but your response ends with `"\",68"`

why does it end with "68" and not "15".I though they all end with "15".Trying to read more data that is available will lead to a hang and i try to avoid that and i though i could avoid it by somehow predicting the end of the data but my prediction seems to fail with your device.

[1] https://github.com/mhogomchungu/ussd-gui/blob/f20794c0280c7a80707fb66b85e8a7aed2184309/src/internal.cpp#L90

[2] https://github.com/mhogomchungu/ussd-gui/blob/f20794c0280c7a80707fb66b85e8a7aed2184309/src/internal.cpp#L106

**Comment by morfikov** [comment] 2016-04-25 17:19
I just checked and all the answers to different codes have 68. Even when I reply to the answers and I get response, it always is 68. The 15 only appears when typing a command, as you can see above. 

> The first response gets parsed

That's not a response, it's just a echo of the typed command. It just tells you what command modem got from you, and that's it.

**Comment by mhogomchungu** [comment] 2016-04-25 17:30
Can you change this line[1] and substitute "15" for "68",compile and try again to see if it now works?

It seems i will have to look into a different way to notice the end of the response.

It will be useful to know what this number represents and why yours is different from mine and if it can be predicted.

[1] https://github.com/mhogomchungu/ussd-gui/blob/f20794c0280c7a80707fb66b85e8a7aed2184309/src/internal.cpp#L106

**Comment by morfikov** [comment] 2016-04-25 17:38
I'll check that in a minute.

**Comment by morfikov** [comment] 2016-04-25 17:44
Yes, that worked.

Also now it doesn't have to wait for 30s timeout. It just returns the answer as soon as it gets it. That's nice.

**Comment by mhogomchungu** [comment] 2016-04-25 18:49
I am glad it worked.

**Comment by mhogomchungu** [comment] 2016-04-26 11:31
There is no longer a need to patch the sources to substitute my "15" to your "68".

Build from updates sources and restart the application and you will see an additional entry in the config file named "terminatorSequence",change the default value to your "68" and restart the application to use the "68" value.

**Comment by morfikov** [comment] 2016-04-26 11:40
Did you figure out why the code in my case is 68? Is it because of a different GSM company, geographic location or a model of the modem? I was searching for this and actually I found only two codes that are used 15, and 68. So maybe it's because of the modem? Maybe the newer ones use 68? What device do you have exactly?

**Comment by mhogomchungu** [comment] 2016-04-26 13:30
I found this link[1] that talks about it,its essentially a variable that has information on how the text was encoded. 

In my case,"15" in decimal means "0000 1111" in binary.

In your case,"68" in decimal means "0100 0100" in binary.

Each one of those bits carries information about the properties of the text and applications i think are expected to be able to make sense of the value and re-encode the text if necessary.In our case,i think we are just lucky that our service providers sent us data already structured in readable form and hence we can ignore the variable with no noticeable effect.

[1] http://stackoverflow.com/questions/23201364/ussd-command-translation

**Comment by mhogomchungu** [comment] 2016-04-26 13:41
The modem has a product ID of "K3772-Z" and it looks like this: https://www.google.com/search?q=K3772-Z&biw=1234&bih=551&tbm=isch&imgil=j5otA1kkmK5iEM%253A%253BUl7BHWp2j0R3cM%253Bhttp%25253A%25252F%25252Fwww.bidorbuy.co.za%25252Fitem%25252F135787736%25252FVODACOM_ZTE_K3772_Z_7_2Mbps_3G_USB_MODEM_OPEN_TO_ALL_NETWORKS.html&source=iu&pf=m&fir=j5otA1kkmK5iEM%253A%252CUl7BHWp2j0R3cM%252C_&usg=__wLaxtZesns4Tre49ldz5plst9jE%3D&ved=0ahUKEwjs7PHNtazMAhVK6xQKHbzxBYkQyjcIQQ&ei=XG4fV-zOJMrWU7zjl8gI#imgrc=j5otA1kkmK5iEM%3A

**Comment by mhogomchungu** [comment] 2016-04-26 15:41
Just tried it on a different modem with a product id of "ZTE WCDMA Technologies MSM" and below is the generated output. It looks like this modem produces text in a way that needs to be re-encoded.

```
[mtz@ink ~]$ ussd-gui -d
"AT+CUSD=1,\"*102#\",15"
"\n\n\nOK\n\n\n\n\nERROR\n\n\n\n+CUSD: 0,\"00530061006C0069006F0020006C0061006B006F003A00200041006B00610075006E007400690020006B00750075003A0054007300680020003100340036002E00300034002C004E0079006F006E00670065007A00610020007900610020004D002D0050006500730061003A00540073006800200030002E004F006E00670065006100200042006F006E00750073003A002000540073006800200030002E00500061007400610020004400410042004F002000420041004E0044004F0020006E00610020004D002D00500065007300610021002000500069006700610020002A003100350030002A00300030002300200063006800610067007500610020006E0075006E007500610020006B00690066007500720075007300680069002E\",72"
[mtz@ink ~]$ 

```

**Comment by morfikov** [comment] 2016-04-26 18:51
There's another problem. After sending a USSD code, I get this:

```
$ ussd-gui -d
"^USSDMODE=1AT+CUSD=1,\"*121#\",15"
```

So there's two commands, and that generates an error and no output.

**Comment by mhogomchungu** [comment] 2016-04-26 18:55
i removed the first command,update your sources and it will be gone

**Comment by morfikov** [comment] 2016-04-26 19:26
That fixed the multi command problem, but there's another problem. Still no results. By cat'ing the device I noticed two things:
1. the command `AT+CUSD=1,"*121#",15` is sent to the modem, but without `OK`. When the `timeout` is reached, `ussd-gui` returns the error `Status: ERROR 5: Connection Timeout.`, and I get `OK` in the `cat` window.
2. When I resend the USSD code, I get different output in the terminal with `cat`. There's `+CME ERROR: 304` right after sending the code, and one additional line `AT+CUSD=2,,15` before `OK` when the `timeout` is reached.

**Comment by mhogomchungu** [comment] 2016-04-26 19:33
You are getting the timeout probably you hang on the reading of data from the device. Are you sure the "terminatorSequence" value in ussd-gui config file is the same as the value you read when you "cat" the output? It was "68" previous in your case.

**Comment by mhogomchungu** [comment] 2016-04-26 19:35
`AT+CUSD=2,,15` is sent to terminate the current session,ie,if the server expects a response,it will keep on expecting until this command is sent or the session times out.

**Comment by morfikov** [comment] 2016-04-26 19:37
I've tested 15, 68 on both interfaces of the modem. There's no difference. My modem don't get any answer now while cat'ing the device. I don't know why, but I'm sure it is related to the delayed `OK` message. In the previous version it was send right away after sending the command. Now there's no `OK` message till `ussd-gui` timeouts.

**Comment by morfikov** [comment] 2016-04-26 19:42
Ok, I've figure that out. `ussd-gui` changed the modem's settings. That;s why I wasn't able to send/receive USSD codes. I had to send:

`$ echo -e "AT+CMGF=1;^CURC=0;^USSDMODE=0\r" > /dev/huawei-E3372-1`

And now it works as expected.

**Comment by mhogomchungu** [comment] 2016-04-26 19:47
Having those settings with my modem causes it to not work and that is why they are commented out in the sources[1]. It seems our modems want contradicting options and i think its better if i dont set them since they dont seem to be universally applicable.

[1] https://github.com/mhogomchungu/ussd-gui/blob/84b2c1379d44977a6183df5581cf7c659f0e5c00/src/internal.cpp#L260

**Comment by morfikov** [comment] 2016-04-26 19:56
You could think about some options that can be customized, like with `terminatorSequence=68` . Then add some info about how to get the values in a manual. Or you could add custom commands in the `ussd-gui` config file. So a person could set the mode and other things. Those commands would be executed before establishing a connection with the modem. Something similar to `wvdial`.

**Comment by mhogomchungu** [comment] 2016-04-27 07:39
The latest commit now sets the device to its default state before starting to use it and this means your `$ echo -e "AT+CMGF=1;^CURC=0;^USSDMODE=0\r" > /dev/huawei-E3372-1` command will be overridden every time you use ussd-gui if they are changing the default state of your device.

The "wvdial" config file you sent me says the command to set the device to its default state is "ATZ",will it not be better to set those options to be the default in your device and then issuing the "ATZ" to load them?

**Comment by mhogomchungu** [comment] 2016-04-27 11:06
Below link has more info about the dcs field

https://en.wikipedia.org/wiki/Data_Coding_Scheme

**Comment by morfikov** [comment] 2016-04-27 12:12
I just copied the info about ATZ command from this pdf http://manuals.world/manuals/huawei/huawei-recording-equipment-mg323.html?page=32 . It's not my model, and some commands used there don't work with my modem and others aren't listed.

**Comment by mhogomchungu** [comment] 2016-07-07 17:50
Do you use wvdial to establish data connection?

If yes,then a Qt5 based GUI front end to wvdial[1] i just create might be useful.

[1] https://github.com/mhogomchungu/wvdial-gui

![screenshot_20160707_204921](https://cloud.githubusercontent.com/assets/3496115/16663336/67ebea3e-4484-11e6-8aec-2ff321c7012c.png)

**Comment by morfikov** [comment] 2016-07-08 05:47
I will try it later.
